# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yac.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1433, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(10, 660, 80, 23))
        self.delete_button.setObjectName("delete_button")
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(-5, 1, 381, 651))
        self.file_list.setObjectName("file_list")
        self.dataset_table = QtWidgets.QTableWidget(self.centralwidget)
        self.dataset_table.setGeometry(QtCore.QRect(395, 1, 1031, 651))
        self.dataset_table.setObjectName("dataset_table")
        self.dataset_table.setColumnCount(0)
        self.dataset_table.setRowCount(0)
        self.remove_row_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_row_button.setGeometry(QtCore.QRect(400, 660, 91, 23))
        self.remove_row_button.setObjectName("remove_row_button")
        self.remove_column_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_column_button.setGeometry(QtCore.QRect(500, 660, 111, 23))
        self.remove_column_button.setObjectName("remove_column_button")
        self.export_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.export_combo_box.setGeometry(QtCore.QRect(1250, 660, 79, 23))
        self.export_combo_box.setObjectName("export_combo_box")
        self.export_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_button.setGeometry(QtCore.QRect(1340, 660, 80, 23))
        self.export_button.setObjectName("export_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1433, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_file = QtWidgets.QAction(MainWindow)
        self.action_add_file.setObjectName("action_add_file")
        self.menuFile.addAction(self.action_add_file)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YAC - Yet Another Converter"))
        self.delete_button.setText(_translate("MainWindow", "Delete File"))
        self.remove_row_button.setText(_translate("MainWindow", "Remove Row"))
        self.remove_column_button.setText(_translate("MainWindow", "Remove Column"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_add_file.setText(_translate("MainWindow", "Add File"))
